filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/app-log.log
      encoding: plain
      fields:
        type: app.log
      fields_under_root: true
      document_type: log
      scan_frequency: 10s
      harvester_buffer_size: 16384
      max_bytes: 10485760

output.kafka:
  hosts: ["kafka:29092"]
        
  topic: 'app-log'
  partition.round_robin:
    reachable_only: false
        
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000    
