CREATE TABLE user (
    uuid VARCHAR(32) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE product (
    uuid VARCHAR(32) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    manufacturerUuid VARCHAR(32) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE manufacturer (
    uuid VARCHAR(32) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
